### ISSUE TITLE
hugo-theme-stackが更新されたときにconflictする可能性がある

### ISSUE THREAD

**Issue by phnyo** [RICORA/blog#10]
現状 .gitignore にthemes/hugo-theme-stack が入っていないので、例えば git commit -a とか git add . とかをして themes/hugo-theme-stack が更新された状態で commit してしまうと master に merge する段階でコンフリクトする可能性があります。  

個人的にはテーマのアップデートは master で一元化して行うべきだと思うのですが、なんかいい解決策とかありますでしょうか。

**Comment by Shinonome517** [comment]
.gitmodulesファイルに

```json
ignore = dirty
```
とすると、submoduleの変更を無視できるみたいです。これを追記しませんか？

[参考](https://scrapbox.io/taka521-tech-notes/%E3%80%90Git%E3%80%91%E3%82%B5%E3%83%96%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%AE%E5%A4%89%E6%9B%B4%E3%82%92%E7%84%A1%E8%A6%96%E3%81%99%E3%82%8B)

**Comment by Shinonome517** [comment]
確認しました。それで行きましょう。

**Comment by phnyo** [comment]
PR出しました。
