### ISSUE TITLE
デフォルトブランチの名前をmainにしたい

### ISSUE THREAD

**Issue by Shinonome517** [RICORA/blog#13]
デフォルトブランチの名前をmainに変えたいです。

理由は、現在のGitHubのデフォルトブランチ名はmainだからです。

その際、リモートのブランチ名を変えることは簡単ですが、そうした場合各個人のローカルクローンを更新する必要があります。一応手間が発生するのでその点のみデメリットです。

[参考](https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

**Comment by phnyo** [comment]
個人的にはどちらでもいいと思います。名前を還るんだったらいまのうちにやっておいた方がいい気がするのでぱぱっと変えちゃった方がいいかもしれません。

**Comment by Shinonome517** [comment]
GitHubの設定もmainブランチになってました

解決です。
ありがとうございました
